### ISSUE TITLE
yup中创建的alertDOM元素不会自动消失

### ISSUE THREAD

**Issue by channingkuo** [yitimo/yeui#1]
在调用alert后，即使点击了确定按钮或点击模态窗部分关闭alert后，在DOM树中穿件的DOM元素还在，没有全部销毁。不知道有没有什么影响。

**Comment by yitimo** [comment]
关闭alert操作会销毁掉属于这个弹窗的DOM，但会留下最外层DOM，这个留下的DOM作为``弹窗插座``，是所有弹出层共用的(接下来可能还会调用别的弹窗)，没有什么销毁的必要。事实上``angular/material``中的弹窗也会留下这么一个DOM。

**Comment by yitimo** [comment]
问题已在``1.6.4``版本中修复, 现在会正确销毁不必要的DOM，只保留一个顶层DOM
